### ISSUE TITLE
The register form for new user doesn't show up

### ISSUE THREAD

**Issue by hoangtuansu** [openhab/openhab-cloud#103]
Hello,

I'm new to Openhab Cloud and try to deploy one for my system. I followed the Installation instruction (and stop at step [Setting up Nginx]. From the log of my console, it seems that I don't have any issue. However, I also post it here if I am wrong.

> d2d_user@d2d:~/Downloads/openhab-cloud$ sudo node app.js
> 2017-05-19T00:32:07.112Z - info: openHAB-cloud: Backend service is starting up...
> 2017-05-19T00:32:07.128Z - info: openHAB-cloud: Backend logging initialized...
> 2017-05-19T00:32:08.450Z - info: openHAB-cloud: Initializing XMPP connection to GCM
> 2017-05-19T00:32:09.773Z - info: openHAB-cloud: Mailer will emulate sending in development environment
> 2017-05-19T00:32:10.181Z - info: openHAB-cloud: Connecting ro Redis at 127.0.0.1:6379
> 2017-05-19T00:32:11.146Z - info: opneHAB-cloud: Trying to connect to mongodb at: mongodb://127.0.0.1/openhab?poolSize=100
> 2017-05-19T00:32:11.178Z - info: openHAB-cloud: Scheduling a statistics job (every 5 min)
> express deprecated app.configure: Check app.get('env') in an if statement app.js:223:5
> express deprecated app.configure: Check app.get('env') in an if statement app.js:227:5
> express deprecated app.configure: Check app.get('env') in an if statement app.js:230:5
> connect deprecated multipart: use parser (multiparty, busboy, formidable) npm module instead node_modules/express/node_modules/connect/lib/middleware/bodyParser.js:56:20
> connect deprecated limit: Restrict request size at location of read node_modules/express/node_modules/connect/lib/middleware/multipart.js:86:15
> connect deprecated methodOverride: use method-override npm module instead app.js:239:21
> 2017-05-19T00:32:11.557Z - info: openHAB-cloud: IFTTT is configured, app handling IFTTT capabilities...
> Option polling duration is not valid. Please refer to the README.
> 2017-05-19T00:32:11.600Z - info: openHAB-cloud: express server listening on port 3000
> 2017-05-19T00:32:11.613Z - info: openHAB-cloud: Redis connect response: OK
> 2017-05-19T00:32:11.616Z - info: Redis is ready
> node_redis: Warning: Redis server does not require a password, but a password was supplied.
> 2017-05-19T00:32:11.658Z - info: openHAB-cloud: Successfully connected to mongodb
> 2017-05-19T00:32:11.871Z - warn: openHAB-cloud: GCM XMPP error: XMPP authentication failure
> 2017-05-19T00:32:13.338Z - info: openHAB-cloud: Authorizing incoming openHAB connection
> 2017-05-19T00:32:13.351Z - info: openHAB-cloud: openHAB b9ac46cd-c977-40b8-9bcb-749a3c12d5e1 not found
> 2017-05-19T00:33:11.180Z - debug: openHAB-cloud: Checking for offline openHABs (0)
> 2017-05-19T00:33:11.181Z - debug: openHAB-cloud: Checking orphaned rest requests (0)
> 2017-05-19T00:34:11.183Z - debug: openHAB-cloud: Checking for offline openHABs (0)
> 2017-05-19T00:34:11.183Z - debug: openHAB-cloud: Checking orphaned rest requests (0)
> 2017-05-19T00:35:00.219Z - info: openHAB-cloud: every5min statistics collection job started
> 2017-05-19T00:35:00.275Z - info: openHAB-cloud: every5min statistics collection job finished
> 2017-05-19T00:35:11.186Z - debug: openHAB-cloud: Checking for offline openHABs (0)
> 

My problem is that I don't see the registration form for new user when accessing to http://localhost:3000. Could someone please give me some advice? 

Thanks,

![oph](https://cloud.githubusercontent.com/assets/75421/26231018/d4b232b6-3c1a-11e7-9185-ed1edd80ba60.png)

**Comment by marziman** [comment]
@hoangtuansu,
welcome to openHAB! All looks fine, you need to activate the registration in the config.json which is false by default.
Please raise your ideas, problems etc first in the community forum at https://community.openhab.org
Iam closing this here.

**Comment by RtjShreyD** [comment]
Hi I have reopened this same [#349 ](https://github.com/openhab/openhab-cloud/issues/349) regarding this, as I tried a lot even after editing `config.json` and setting the `registration_enabled=true` still does not seem to work. Please put some light on this.
