### ISSUE TITLE
Add support for Google Assistant Integration

### ISSUE THREAD

**Issue by fabito** [openhab/openhab-cloud#107]
Implement the endpoints needed for building Smart Home apps as specified here: https://developers.google.com/actions/smarthome/

Such an app would allow controlling openhab items thorough google assistants.

There is an example implementation here https://github.com/actions-on-google/actionssdk-smart-home-nodejs

**Comment by marziman** [comment]
@fabito,
thank you! this is already in the making if you are a little patient. Needs a little time.
I will keep you updated here:
https://community.openhab.org/t/google-home-actions-api-now-available/17917/21

**Comment by ehorohorin** [comment]
Any updates on this? Many thanks
