### ISSUE TITLE
Smoke tests for openHAB-cloud

### ISSUE THREAD

**Issue by FlorianSW** [openhab/openhab-cloud#113]
In PR #97 and in some others I don't remember anymore, I made some changes and updated the PR with a merge of master and made a simple small mistake during the conflict resolution. While I would agree, that I would need to be more careful about these little kind of things (:P), I would love some smoke tests more :D

In my vision the tests would try to run app.js and look at any error message during startup and fail, if there're any and stop the instance and proceed with unit tests after it. We could probably extend the tests with requesting some endpoints later, however, just starting app.js sounds like a good idea for now.

**Comment by digitaldan** [comment]
openHAB has both a TravisCI and cloudbees account for builds and testing,   if someone wants to tackle this I would be happy to get them access to one or both.

**Comment by marziman** [comment]
@digitaldan & FlorianSW,

I was thinking about this also since long, but had a lot to do. I would tackle it after I finished the Google Home openHAB action (thats why I am a little quite :-) ).
So if you and @FlorianSW say yes, you can "assign" it to me.
@FlorianSW: Did I had any review open? I am in the believing I reviewed and merged the stuff?!

Br Mehmet

**Comment by FlorianSW** [comment]
From my point of view, the tests should be runnable on every system, so everyone would be able to setup the repo to allow running each kind of test (e.g. as an npm task or bundled with npm test). Afterwards we can take a look how and what tests we will run using Travis or Jenkins :)

@marziman I think there's no open PR that explicitly needs a review from you, except probably #98, however,  @digitaldan is already quite active there :)

**Comment by marziman** [comment]
Closing this with https://github.com/openhab/openhab-cloud/pull/122
and opening other issues for the tasks
