### ISSUE TITLE
Update current Nodejs for latest Security Fixes

### ISSUE THREAD

**Issue by marziman** [openhab/openhab-cloud#114]
There is a new Security update for all Nodejs release lines. This update needs to be done to fix e.g. security vulnerabilities:
https://nodejs.org/en/blog/vulnerability/july-2017-security-releases/

**Comment by FlorianSW** [comment]
Hmm, this seems not to be an issue for openhab-cloud itself, right? We don't ship any nodejs version, and therefore do not need to update anything? :)

**Comment by marziman** [comment]
Partly true. It was a reminder to raise the node version due to the security patch.
In our docker image we ship a docker file with node, where I have raised the version aready.
