### ISSUE TITLE
Docker images not working

### ISSUE THREAD

**Issue by hakonrossebo** [openhab/openhab-cloud#117]
The nodejs image seems to report issues with bcrypt versions in use. Does anyone else have this issue?

**Comment by FlorianSW** [comment]
Can you post an error message or something? :)

**Comment by hakonrossebo** [comment]
This is the log from app-1 after running docker-compose up:

<details>
λ docker-compose logs app-1
Attaching to app-1
app-1      | 2017-08-08T07:57:34.046Z - info: openHAB-cloud: Backend service is starting up...
app-1      | 2017-08-08T07:57:34.053Z - info: openHAB-cloud: Backend logging initialized...
app-1      | 2017-08-08T07:57:34.297Z - error: uncaughtException: Error relocating /opt/openhabcloud/node_modules/bcrypt/lib/binding/bcrypt_lib.node: __snprintf_chk: symbol not found date=Tue Aug 08 2017 09:57:34 GMT+0200 (CEST), pid=1, uid=100, gid=65533, cwd=/opt/openhabcloud, execPath=/usr/bin/node, version=v7.5.0, argv=[/usr/bin/node, /opt/openhabcloud/app.js], rss=45608960, heapTotal=23048192, heapUsed=13690232, external=17969345, loadavg=[1.40966796875, 0.62939453125, 0.27783203125], uptime=17637, trace=[column=18, file=module.js, function=Module._extensions..node, line=598, method=.node, native=false, column=32, file=module.js, function=Module.load, line=488, method=load, native=false, column=12, file=module.js, function=tryModuleLoad, line=447, method=null, native=false, column=3, file=module.js, function=Module._load, line=439, method=_load, native=false, column=17, file=module.js, function=Module.require, line=498, method=require, native=false, column=19, file=internal/module.js, function=require, line=20, method=null, native=false, column=16, file=/opt/openhabcloud/node_modules/bcrypt/bcrypt.js, function=null, line=6, method=null, native=false, column=32, file=module.js, function=Module._compile, line=571, method=_compile, native=false, column=10, file=module.js, function=Module._extensions..js, line=580, method=.js, native=false, column=32, file=module.js, function=Module.load, line=488, method=load, native=false, column=12, file=module.js, function=tryModuleLoad, line=447, method=null, native=false, column=3, file=module.js, function=Module._load, line=439, method=_load, native=false, column=17, file=module.js, function=Module.require, line=498, method=require, native=false, column=19, file=internal/module.js, function=require, line=20, method=null, native=false, column=14, file=/opt/openhabcloud/models/userdevice.js, function=null, line=3, method=null, native=false, column=32, file=module.js, function=Module._compile, line=571, method=_compile, native=false], stack=[Error: Error relocating /opt/openhabcloud/node_modules/bcrypt/lib/binding/bcrypt_lib.node: __snprintf_chk: symbol not found,
  at Object.Module._extensions..node (module.js:598:18),     at Module.load (module.js:488:32),     at tryModuleLoad (module.js:447:12),     at Function.Module._load (module.js:439:3),     at Module.require (module.js:498:17),     at require (internal/module.js:20:19),     at Object.<anonymous> (/opt/openhabcloud/node_modules/bcrypt/bcrypt.js:6:16),     at Module._compile (module.js:571:32),     at Object.Module._extensions..js (module.js:580:10),     at Module.load (module.js:488:32),     at tryModuleLoad (module.js:447:12),     at Function.Module._load (module.js:439:3),     at Module.require (module.js:498:17),     at require (internal/module.js:20:19),     at Object.<anonymous> (/opt/openhabcloud/models/userdevice.js:3:14),     at Module._compile (module.js:571:32)]
app-1      | 2017-08-08T07:57:34.299Z - error:
app-1      | 2017-08-08T07:57:36.965Z - info: openHAB-cloud: Backend service is starting up...
app-1      | 2017-08-08T07:57:36.972Z - info: openHAB-cloud: Backend logging initialized...
</details>

**Comment by marziman** [comment]
hi @hakonrossebo ,

this bcrypt is a real snake :-)
So I found that issue after searching some time. It is due to binary problems of Alpines used musl libc and was tricky, since it just popped up by "nothing".
Please update your oh-cloud project to the latest version and run docker-compose up as stated in the readme.

"Alpine linux based images use musl libc instead of the standard glibc and thus are not compatible with compiled binaries. node-pre-gyp currently does not test the pre-compiled binaries to be ABI-compatible and thus you may see segfaults. We are working to resolve this issue.

As a workaround, In alpine based images, force recompiling the bcrypt native addon after a npm install with this command: npm rebuild bcrypt --build-from-source"

**Comment by hakonrossebo** [comment]
Thanks :)
