### ISSUE TITLE
Docker image

### ISSUE THREAD

**Issue by RyanRamchandar** [openhab/openhab-cloud#12]
A docker image with all the necessary dependencies installed for you would be a great way to get up and running quickly.

**Comment by marziman** [comment]
@RyanRamchandar,

yes we are already planning to create an image.
Thanks for your input

**Comment by medom** [comment]
has there been any progress on this subject yet? :)

**Comment by marziman** [comment]
@medom,

we ve already started this and if you are a little patient and wait, there will be a docker image soon. At the moment there are some other urgent issues. I will keep you updated here..

BR Mehmet

**Comment by marziman** [comment]
Hi,

I will update the state here. The initial PR is there:
https://github.com/openhab/openhab-cloud/pull/91
As soon I got the docu and the final review+meege I will notify and close this issue.
There is still some small nginx problem with css Iam struggling with.
BR Mehmet

**Comment by marziman** [comment]
Solved by https://github.com/openhab/openhab-cloud/pull/91
