### ISSUE TITLE
Can't access dashboard or community

### ISSUE THREAD

**Issue by mavris** [openhab/openhab-cloud#127]
Dashboard or community.openhab.org fail with error 504 Gateway Time-out.
Is it only me?

**Comment by kaikreuzer** [comment]
Please don't use the issue tracker here, but check http://status.openhab.org/ to find the answer.

**Comment by mavris** [comment]
sorry I wasn't aware. Thank you

**Comment by kaikreuzer** [comment]
Sorry for the inconvenience - @marziman and @digitaldan are working hard on resolving the issues! (I already failed...)
