### ISSUE TITLE
Extend docu for the E2E chain with OH Cloud Connector after setup of an instance

### ISSUE THREAD

**Issue by marziman** [openhab/openhab-cloud#13]
We should extend the docu, showing the last steps for connecting your oh against your own instance.

**Comment by kirantpatil** [comment]
Hi @marziman, 

I would like to know whether openhab-cloud works with/supports ESH.

Have you tested it with ESH ?
 
I am raising it here, since I did not get any response from openhab-cloud developers at [community.openhab.org](https://community.openhab.org/t/openhab-cloud-for-esh/22384/2).

**Comment by marziman** [comment]
I think this should be closed, since there is official docu about how to setup at docs.openhab.org.
Closing this!
