### ISSUE TITLE
Handling Custom Websocket Request for Custom UI

### ISSUE THREAD

**Issue by lsafelix75** [openhab/openhab-cloud#143]
Hi

I managed to make some changes to Openhab Cloud code and Connector in order to handle external Websocket requests for 3rd party WebGUI such as NodeRed. I'm not sure whether OpenHab is keen in this direction. From my stand point, i feel that this is necessary since we can develop our own UI (that incorporate any web technologies) and OpenHab rule engine is still in infant stage and not user friendly (hence more matured Nodered is requires).  If so, I can share with you all my sketchy codes and hopefully someone can incorporate them into future release. cheers

**Comment by marziman** [comment]
Hi @Isafelix75,

thanks for your ideas and support. I would propose to close this issue here and point you to https://community.openhab.org to discuss in the community and speak afterwards about solutions?

Sure, feel fre to contribute. But lets first discuss all together in the forum.

BR Mehmet
