### ISSUE TITLE
Apple Notifications issues

### ISSUE THREAD

**Issue by digitaldan** [openhab/openhab-cloud#151]
@FlorianSW we just deployed the latest code that includes the new routes (from Aug), I know that was a while ago :-)   There seems to be a few issues at least with the Apple Notification class, I have it crudely patched in production, but I was hoping for a more elegant fix.

on https://github.com/openhab/openhab-cloud/blob/master/mobileregistrationservice/AppleRegistrationService.js#L28 this probably needs to be self.getDeviceId as it was throwing an error that deviceId was not defined

also the same here https://github.com/openhab/openhab-cloud/blob/master/mobileregistrationservice/AppleRegistrationService.js#L52 

Finally https://github.com/openhab/openhab-cloud/blob/master/mobileregistrationservice/AppleRegistrationService.js#L48 throws an error that it can't instantiate info on an undefined object, so getLogger is returning undefined.

can you take a look?

**Comment by FlorianSW** [comment]
I'll take a look into this! Sorry for the problems that this made :/

**Comment by EjvindHald** [comment]
The IOS app has recently not been updating icons using myOopenHAB when the state changes, and it used to work perfectly. Now the icons in the IOS app only change state correct, if it is a local connection.

See examples:
[here](https://community.openhab.org/t/latest-ios-app-bugs/36771/16)
and [here](https://community.openhab.org/t/myopenhab-not-displaying-images-icons-correctly/39272)
