### ISSUE TITLE
Docker image on Raspberry Pi

### ISSUE THREAD

**Issue by ScheissSchiesser** [openhab/openhab-cloud#152]
I am attempting to spin up the docker image for openhab-cloud on my raspberry pi 2 running raspbian jessie.
`pi@rpij:~/openhab-cloud $ sudo docker-compose up -d --force-recreate`
`Building mongodb`
`Step 1/2 : FROM mongo:3`
`3: Pulling from library/mongo`
`ERROR: Service 'mongodb' failed to build: no matching manifest for linux/arm in the manifest list entries`

It seems as though docker does not have armhf images of mongodb to pull from. Is there any way around this?

**Comment by marziman** [comment]
Hi,

I think you need to pull the right mongo ARM image from DockerHub (e.g.https://hub.docker.com/r/partlab/ubuntu-arm-mongodb/). But since this is not an issue related to openhab-cloud, I would close this here.

BR Mehmet
