### ISSUE TITLE
"Internal Server Error" on applications page

### ISSUE THREAD

**Issue by kaikreuzer** [openhab/openhab-cloud#157]
Accessing https://myopenhab.org/applications on my account results in an "Internal Server Error" response from the server - I therefore have no chance to manage my applications anymore :-(

**Comment by kaikreuzer** [comment]
@digitaldan Any chance to address this?

**Comment by marziman** [comment]
@kaikreuzer,
I prepared a fix. It was too late today and I was busy with Google folks.
I will let you know, soon.

**Comment by marziman** [comment]
I hope it was not the missing icon of Google Assistant. This shouldnt throw an internal server error. I will see tomorrow.

**Comment by kaikreuzer** [comment]
Thanks @marziman!

**Comment by kaikreuzer** [comment]
According to @marziman this was some old test token in the database - after cleaning it, the problem is gone.
I'd leave that issue open though as even invalid tokens should not result in such an error in the UI.

**Comment by marziman** [comment]
Hi,

I could not reproduce this. So I would close it for now.
I was related to some inconsistent database state.
