### ISSUE TITLE
Charts not correctly rendered

### ISSUE THREAD

**Issue by kaikreuzer** [openhab/openhab-cloud#163]
When using the remote connectrion, the charts are not rendered correctly, sometimes we only get an empty chart with the default white theme, sometimes the correct rendering.

There is not such a problem when using the local wifi connection. In this case, rendering is always good.

Lots of users have noticed that problem and you have several topics on the forum about this problem. Few users are even mentioning that all images are concerned, that is images, icons and charts.

**Comment by kaikreuzer** [comment]
Originally reported as https://github.com/openhab/openhab-android/issues/694.

**Comment by kaikreuzer** [comment]
@digitaldan This is the known issue that I had reported privately directly after the myopenhab update a few weeks ago.

I think it is a critical issue that needs to be resolved asap.

**Comment by e-rook** [comment]
I think it is related to how mobile apps are integrated with cloud - because if I check sitemap using basicUI https://home.myopenhab.org/basicui/app all charts are rendered correctly. At the same time iOS and Android apps fails. So question is how charts are fetched by mobile apps?
