### ISSUE TITLE
[Feature Request] Remote debugging using openhab-cloud

### ISSUE THREAD

**Issue by kirantpatil** [openhab/openhab-cloud#164]
Hi,

I would like login to my system for diagnostic purpose(May be just use Terminal to login), to resolve any issue (Ex. RAM is full, so I need to restart openhab, To verify openhab configurations and so on ..)

Any Ideas, Please throw some light on it.

Thanks.

**Comment by lsafelix75** [comment]
You need web based ssh to make this work. I have done it but it is not a simple solution as you need to modify openhabcloud code, host the modified openhabcloud, build your own openHAB UI bundle to handle webshell

**Comment by kirantpatil** [comment]
Thanks for the suggestion.

So, we need build or integrate app like https://github.com/billchurch/WebSSH2 with openhab-cloud right ?

**Comment by kirantpatil** [comment]
@Isafelix75, Could you please share your ssh solution ?

**Comment by lucacalcaterra** [comment]
I use wetty  As docker container..

**Comment by kirantpatil** [comment]
Cool, I would like to remote ssh access from myopenhab user account.

Please throw some light on it.

**Comment by kirantpatil** [comment]
Finally, we found a solution to login to remote system using reverse ssh using central server rather openhab-cloud.

https://bitbucket.org/marcpearson/sshmein/wiki/Home
