### ISSUE TITLE
Image item from IP Camera starting data too soon, stopping control page from opening and not stopping right away.

### ISSUE THREAD

**Issue by Skinah** [openhab/openhab-cloud#191]
So I did my first test using the Cloud to view my IP camera with the binding I am writing and the result may have turned up a bug. I am updating an IMAGE item with a jpg that is 130kB once every second, and I only have "notifications and remote access" enabled in the cloud setup. No items are exposed, my list is empty.

I used openHAB.org to log in and view my camera via basicUI, the image did not update as often as the server and when I left the data stopped. No big deal if the image is only updated X% of the time, at least it works and then stops when I leave the sitemap page to another room of my house with no camera viewing.

I then tried using openHAB.org to view the camera using PaperUI and the control section. The moment I opened Paperui the data rate went up and I had not started viewing the camera as the page was still sitting at the INBOX. I then tried to click on the control section and it would not load or would not load all the 30+ things that I have. I closed paperUI and my out going data did not drop and stayed up, my router shows it is sending the 130kB snapshot every second and this does not stop right away. The first time it took 5 minutes or so to stop on its own although I was not timing it, this is a guess. I tested this a second time and it timed it and was around 2 minutes the second time for the traffic to stop after I had closed the broswer.

So it appears the PaperUI will start loading my image channel when I am not even viewing it. The control page not loading fully I would need to do some tests to determine if it is my image channel that causes it to not load, but I suspect that it is the cause.

Is this 1/2 bugs or am I doing something wrong and can I provide any more information to assist?

**Comment by Skinah** [comment]
Some comments and further information are located here in the forum.
https://community.openhab.org/t/bandwidth-limits-and-playing-nice-with-myopenhab-org-openhab-cloud/44107/7

**Comment by kaikreuzer** [comment]
> I am updating an IMAGE item with a jpg that is 130kB once every second

I'd say this is the main problem - Paper UI subscribes on every event change through SSE and all those images are sent as status updates. Doing an image item update should happen only, if there is some relevant change.

**Comment by digitaldan** [comment]
The cloud service proxies requests as fast as it can, but if there is a lot of data, like an image changing that quickly, its going to get slow.  In fact, if you have a bunch of requests for data outstanding, and then close the web page, our cloud connector add-on will most likely try and fulfill those requests, even though there's nothing there to receive it.  I would say this is not a good use case for the cloud service
