### ISSUE TITLE
Node goes to 100% cpu and stops accepting connections

### ISSUE THREAD

**Issue by digitaldan** [openhab/openhab-cloud#20]
At some point the node process will eat up 100% of cpu and stop accepting new connections.  While load over time causes this to happen, high load itself is not the issue as restarting the process and taking on the previous load will clear the issue for a few days.

**Comment by marziman** [comment]
@digitaldan could this be in relation to how the app is started? I think if the app is started with NODE_ENV = development or not set, it will be automatically set to development, which could be the reason for eating up CPU due to highly fragmented functions activated at dev.

**Comment by digitaldan** [comment]
@marziman I'm not sure I understand what you mean? But we do run this with NODE_ENV = production, but I guess i don't know why running it =development would cause issues, have you seen this personally?

**Comment by marziman** [comment]
Hi @MHerbst,
Thanks! I will take some time and investigate this deeper, since actually this issue it is causing reboots. I also looked into this:
https://github.com/sidorares/node-tick
I will inform about the progress..
BR Mehmet

**Comment by marziman** [comment]
@digitaldan,
should we keep this issue and try to analyze? We are actually running under 90% CPU ..just wanted to ask if we should keep this issue as is?
Your nginx seperation helped alot from my point of view

**Comment by marziman** [comment]
@digitaldan I am closing this.
If it comes back as problem, we can reopen it? Actually the CPU behavior looks good after your tweaks. Hope this is ok for you.
