### ISSUE TITLE
504 Gateway Time-out on REST DELETE

### ISSUE THREAD

**Issue by brookstudio** [openhab/openhab-cloud#200]
**Summary:**
Attempting to use the paper-ui remotely through myopenhab to delete a thing, and it appears that most of the paper-ui works fine, except for DELETEs. This is similar as #31 

The paper-ui works fine when locally, so this appears likely to be bug with the routing rules between the nginx accepting frontend and whatever service is relaying that post back to the local instance.

**Sanitized Request headers:**
```
Request URL: https://home.myopenhab.org/rest/things/fitbit:door_sensor:3713?force=false
Request Method: DELETE
Status Code: 504 Gateway Time-out
Referrer Policy: no-referrer-when-downgrade
Accept: application/json, text/plain, */*
Accept-Encoding: gzip, deflate, br
Accept-Language: zh-CN,zh;q=0.9,en;q=0.8
Connection: keep-alive
Cookie: <redacted>
DNT: 1
Host: home.myopenhab.org
Origin: https://home.myopenhab.org
Referer: https://home.myopenhab.org/paperui/index.html
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36
```

**Response**

```
Connection: keep-alive
Content-Length: 594
Content-Type: text/html; charset=utf-8
Date: Sat, 26 May 2018 12:41:43 GMT
Server: nginx/1.10.0 (Ubuntu)
```

**Comment by lsafelix75** [comment]
https://community.openhab.org/t/unsupported-request-method-delete/39629

I reported this before via openhab forum

**Comment by favors** [comment]
Please close this. I investigate and found it's a issue from openhabcloud binding and should be fixed there. Thanks.

**Comment by mystdeim** [comment]
I still get this error on every detele request
