### ISSUE TITLE
How to connect ifttt openhab service to my own openhab-cloud server

### ISSUE THREAD

**Issue by sagittarius0815** [openhab/openhab-cloud#204]
Is there any documentatin how to connect ifttt service to my own openhab-cloud server?
I have my own openhab-cloud server running, but the ifttt service allways tries to connect to https://myopenhab.org. Is it no intended to connect ifttt openhab service to an own server?

**Comment by digitaldan** [comment]
There is not, you would have to sign up as a service provider with IFTTT, theres no way of using the official openHAB IFTTT with your own instance.

**Comment by sagittarius0815** [comment]
OK, I understand!
The IFTTT API is a part of the openhab-cloud server.
I have to configure my own IFTTT service via IFTTT platform.
With some help for configuring OAuth2 I've got it running.
