### ISSUE TITLE
Unable to Reset Password

### ISSUE THREAD

**Issue by jarrodlucia** [openhab/openhab-cloud#208]
I have reset password many time now, with different combinations. Each time I am unable to login with the new password. 

Is there a way to deregister the email and reregister again.

**Comment by marziman** [comment]
Hi @jarrodlucia,

I will take a look at this.
Can you send a mail to the support email?

Thanks

**Comment by peter9208** [comment]
Hi @marziman, @jarrodlucia 
There was a bug in routes/account.js at line 113, though that has been fixed since I discovered (unfortunately I had no time to create a pr then).
It was fixed by @digitaldan  a few days ago.

I think that issue can be closed now.

**Comment by digitaldan** [comment]
Thanks @peter9208 , i will close this issue.
