### ISSUE TITLE
i am running a openhab-cloud instance in my localhost 

### ISSUE THREAD

**Issue by turagabhupathi** [openhab/openhab-cloud#210]
i am getting offline all the time when i am login with my uuid and secret

**Comment by kirantpatil** [comment]
Have you connected Openhab instance to it using openhab-cloud connector ?

**Comment by kirantpatil** [comment]
Please use [forum](https://community.openhab.org/) for such questions and close this issue.

**Comment by kirantpatil** [comment]
Forum has same question.

https://community.openhab.org/t/myopenhab-always-offline/42397
