### ISSUE TITLE
504 Gateway Time-out

### ISSUE THREAD

**Issue by Alshukaily** [openhab/openhab-cloud#221]
It's starts yesterday when I tried open garage door using Google assistant and it couldn't connect then I tried to open openhab app but also not connected. So I don't know what happened. There is no changes has been made during the past three days, except I have noticed the app has been updated overnight before, but I checked the remote access username and password but they still there.
Then I tried to access from myopenhab.org I have got this error "504 Gateway Time-out"

**Comment by roberlax** [comment]
I have the same issue since yesterday.
Additionally I noticed, that cloud access was quite slow since some days.

**Comment by Stefan300381** [comment]
same here. Google occasionally responds in German "Der Anbieter openhab ist nicht erreichbar" (openhab is not available). Just right now I have switche on a light in my office room, then 2s later I try to turn it off and I hear the error message.

**Comment by Luix87** [comment]
Same here, it’s there an issue with OpenHAB cloud in these days?? Can someone throw a light around here on what’s going on??

**Comment by roberlax** [comment]
Issue now dissappeared on my side. Would be really interesting what causes such effects.

**Comment by Alshukaily** [comment]
Also from my side..I just checked it's working

**Comment by kaikreuzer** [comment]
See https://community.openhab.org/t/solved-is-home-myopenhab-org-down/54000/49.

I'd assume we can close this now.

**Comment by pinki** [comment]
I get 504 errors since this morning.
