### ISSUE TITLE
while running node app.js . it is throwing error

### ISSUE THREAD

**Issue by vivekpratap007** [openhab/openhab-cloud#236]
sudo node app.js
Option polling duration is not valid. Please refer to the README.
(node:4979) DeprecationWarning: current URL string parser is deprecated, and will be removed in a future version. To use the new parser, pass 
option { useNewUrlParser: true } to MongoClient.connect.
node_redis: Warning: Redis server does not require a password, but a password was supplied.
(node:4979) DeprecationWarning: collection.ensureIndex is deprecated. Use createIndexes instead.

Please have a look.

**Comment by vivekpratap007** [comment]
I am in  current master branch

**Comment by lucacalcaterra** [comment]
All advices are warningsm so your app should must be running anyway (in my experience, i've the same warnings)... can you connect to the localhost:3000 ?

By the way...
-Option polling duration is not valid... don't know
- The last two error should be related to redis and mongo password... probably you have specified password but not needed because the server not require authentication for the db.

**Comment by vivekpratap007** [comment]
Thank @lucacalcaterra 
yes you are right , last two are the warings .
Now we have chosen the  the latest stable version  and we are not facing any issue,

thanks,

**Comment by ultra-pool** [comment]
Mine just shows "~/openhab-cloud# sudo node app.js
Option polling duration is not valid. Please refer to the README."
No errors below it.
Ubuntu 16 64bit

**Comment by lsafelix75** [comment]
I am seeing the following messages though with latest pull from git:

> Option polling duration is not valid. Please refer to the README.
> (node:23733) DeprecationWarning: current URL string parser is deprecated, and will be removed in a future version. To use the new parser, pass option { useNewUrlParser: true } to MongoClient.connect.
> (node:23733) DeprecationWarning: current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.
> node_redis: Warning: Redis server does not require a password, but a password was supplied.
> node_redis: Warning: Redis server does not require a password, but a password was supplied.
> node_redis: Warning: Redis server does not require a password, but a password was supplied.
> (node:23733) DeprecationWarning: collection.ensureIndex is deprecated. Use createIndexes instead.

**Comment by joshuakoh1** [comment]
How did you solve this?
