### ISSUE TITLE
Online link points to Event log and shows no events

### ISSUE THREAD

**Issue by kirantpatil** [openhab/openhab-cloud#24]
I clicked on "Online" link and it is pointing to "Event log" http://xx.xxx.x.xxx:3000/events?source=openhab and not showing any events.

If I click on "Event log" http://xx.xx.x.xxx:3000/events link, it shows events.

#### http://xx.xxx.x.xxx:3000/events?source=openhab
----
![screenshot from 2017-01-10 18 32 36](https://cloud.githubusercontent.com/assets/1178055/21807488/f859640c-d764-11e6-8993-a7352a906abc.png)

#### http://xx.xx.x.xxx:3000/events
----
![screenshot from 2017-01-10 18 40 45](https://cloud.githubusercontent.com/assets/1178055/21807485/f3f6e574-d764-11e6-87dc-628b241c4f60.png)

**Comment by marziman** [comment]
@kirantpatil this are different views. The one shows event log and the other one shows the "online" status in a similar view. But when you look at where, you see that the info differs. It works correct and show the "ONLINE STATUS". Can you please ask in the forum before, than we can clear these things before opening an item for it?
Iam closing this here an we can switch the discussion to forum if really needed.

**Comment by kirantpatil** [comment]
Initially I thought of using forum, but felt could be issue so raised here.
Thank you.
