### ISSUE TITLE
Problems with starting on Debian 9 on VPS

### ISSUE THREAD

**Issue by cookins** [openhab/openhab-cloud#243]
Hi
I want to install OpenHAB on remote VPS for smart home.
So i installing from rep and got some problems:
```
[admin@****** ~]# /etc/init.d/openhab2 status
● openhab2.service - openHAB 2 - empowering the smart home
   Loaded: loaded (/usr/lib/systemd/system/openhab2.service; disabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Sat 2019-02-23 03:36:06 EET; 1s ago
     Docs: https://www.openhab.org/docs/
           https://community.openhab.org
  Process: 5729 ExecStop=/usr/share/openhab2/runtime/bin/karaf stop (code=exited, status=1/FAILURE)
  Process: 5714 ExecStart=/usr/share/openhab2/runtime/bin/karaf $OPENHAB_STARTMODE (code=exited, status=1/FAILURE)
 Main PID: 5714 (code=exited, status=1/FAILURE)

Feb 23 03:36:06 ********.net systemd[1]: openhab2.service: Control process exited, code=exited status=1
Feb 23 03:36:06 ********.net systemd[1]: openhab2.service: Unit entered failed state.
Feb 23 03:36:06 ********.net systemd[1]: openhab2.service: Failed with result 'exit-code'.
```
any hints?
thanks!

**Comment by cookins** [comment]
anybody?
is that even official openhab?

**Comment by digitaldan** [comment]
Hi @cookins , this is the repo for our Cloud proxy service, not the main openHAB project.  There are only a few who monitor tickets here.

But i think in your case you would be better to ask your question on the forum  at https://community.openhab.org/ , there are significantly more people there that can help out and answer questions.

I will also suggest that you post the logs files too (/var/log/openhab.log), i don't think the info above would be enough to trouble shoot.  

Thanks!
