### ISSUE TITLE
Dashboard, Android app and Google service -504 Gateway Time-out

### ISSUE THREAD

**Issue by Landstad** [openhab/openhab-cloud#251]
After the recent deploy clicking on items in the event log works and also choosing page x.

But everything else stopped working (i e, dashboards, Android App, Google service).

Dashboard: 
I click "Click here to access your openHAB's dashboard"
After a minute I get the 504.

Android app: 
I open the app, after a minute I get the 504.

Google Service:
If I use voice:
"OpenHAB seems to be unavailable right now."
Google Home devices:
"Not responding"

**Comment by digitaldan** [comment]
Can you try restarting your openHAB instance, or just restart the openHAB Cloud binding?

**Comment by Landstad** [comment]
Restarting openHAB worked. Thank you.
