### ISSUE TITLE
Receiving push notifications from / for other users 

### ISSUE THREAD

**Issue by redeye86** [openhab/openhab-cloud#252]
I received two push notifications yesterday and a few minutes ago that were not sent by my own installation of openhab and were not sent to me actually. 

I (and other users) already had this Issue a year and a half ago or so. As far as I remeber this occurred after down time of the cloud service.

I think this is really critical as personal information is sent to wrong recipients.

**Comment by digitaldan** [comment]
I am currently looking at this now.

**Comment by digitaldan** [comment]
@maniac103 I am currently doing a review of recent code changes and noticed that `data` had local scope before your change, but now is global, can you look at https://github.com/openhab/openhab-cloud/blob/90cb7383ce3215d670b9591cab154a1c4c34356a/notificationsender/firebase.js#L17

**Comment by maniac103** [comment]
> noticed that data had local scope before your change, but now is global

@digitaldan What do you mean by 'now is global'? `data` is passed in as function parameter there, it still has local scope (in the calling functions `sendMessageNotification` and `sendNotification`) AFAICT.

**Comment by digitaldan** [comment]
Your right, i missed that :-)

**Comment by digitaldan** [comment]
@FlorianSW  can you look at change you made in #188 ?  Specifically this line?  https://github.com/openhab/openhab-cloud/blob/639fdad9117672d552266ae266c75785e5883c8b/app.js#L354  I think we have this accidentally as a global and maybe causing messages to go to the wrong place under load.  (not 100% sure, i'm still looking )

**Comment by FlorianSW** [comment]
It seems to be correct, that this variable is misleadingly declared as a global one (while it should be in the scope of the function). However, I'm unsure, if this could lead to the problem mentioned in this issue. So, as this seems to be wrong obviously, I created #253 to fix it. Let's see if this is also the cause of the wrong sended messages :)

**Comment by digitaldan** [comment]
Thanks @FlorianSW !   I hope we found this issue, i just deployed this and restarted services.

**Comment by digitaldan** [comment]
Seems to be fixed, thanks all!
