### ISSUE TITLE
API to retrieve current userID for Google assistant

### ISSUE THREAD

**Issue by RayBa82** [openhab/openhab-cloud#262]
I developed a google assistant action to control openHAB based on the official Google samples and marzimans work (which works great and without the annoying bug if you execute rules), and integrated the ReportState functionality.
Google requires a userID in the responses, but right now there is no way to get the userId via API and valid token, is that right?

For a valid google assistant integration, there has to be a possibility to get a userId via REST API, this can be a hashed String, it just has to be unique for a user.

**Comment by RayBa82** [comment]
I have created a PR #265 which adds a few lines to get this API

**Comment by digitaldan** [comment]
Questions, how does the official openHAB integration with google assistant work without this ID?  Are you planning on making this available as a community project or is this private?  Or, Are you planning on introducing this as an enhancement to the existing openHAB assistant?

**Comment by RayBa82** [comment]
After some investigation this PR is obsolete, since OpenHAB has no user concept it is better to use the uuid for identification.

The official Google assistant integration does not use it at all, since it has not implemented the report state functionality, which is now a requirement to get actions deplyoed. Projects which were deplyoed before this requirement was introduced do still work, which is the case for the openhab integration.

My version of the integration is a bit different to the original since it is a nodejs application, not just some javascript files deployed to a storage bucket. It has to run either in Google App Engine or on any other server. 
I think it is not possible to integrate this in the original assistant integration, but i plan to make this repository public available.

It would probably be easier to directly integrate it in the openhab-cloud project, since it is a nodejs application too.

**Comment by kirantpatil** [comment]
Hi @RayBa82,

Good to know that finally you could do it. 

We were trying to build Report State integration with current Google assistant integration and share it with community. We are struck in passing the testcases and once you share your code, then we will have a look over it to figure out why it is not possible to integrate with current code.

Awaiting your valuable guidance along with code.

Thanks,
Kiran.

**Comment by RayBa82** [comment]
My code is absolutely no magic.
It is completely based on this example https://github.com/actions-on-google/smart-home-nodejs
All calls to firestore have been replaced with calls to OpenHAB REST API thats all. Report State works out of the box. As useragentID the OpenHAB uuid is used.

Took me a few hours to get it up and running, mostly converting js to typescript.

**Comment by pratapvivek007** [comment]
@RayBa82 
It's good to know that it was no big deal for you.
When I was trying , i was getting issue while testing with "Smart Home Test Suite (https://smart-home-test-suite.firebaseapp.com/)" which is for "generate the report status" and send to Google team for certification.
I would like to know that how was your report state result.?
Is it possible to share your repo link where you have updated your modified code .
Thanks,

**Comment by kirantpatil** [comment]
Here is our code and also please let us know what modification do we need to make.

[chiruopenhab.txt](https://github.com/openhab/openhab-cloud/files/3272150/chiruopenhab.txt)

Thanks,
Kiran.

**Comment by kirantpatil** [comment]
Hi All,

We have done it and soon we will publish the code to community.

Thanks.

**Comment by RayBa82** [comment]
Since this topic is obsolete i will close this issue now
