### ISSUE TITLE
iOS devices not showing up in the myopenHAB.org device list

### ISSUE THREAD

**Issue by Gibber** [openhab/openhab-cloud#27]
Ever since the change over to myopenHAB.org, my apple devices have not shown up in the devices list under my account. My android device shows up, and the apple devices all work fine through the remote URL. They just don't show up in the devices list. I tried uninstalling and reinstalling the app on a couple of the devices but that did not help. I am using iOS app version 1.7.4 on a couple of different versions of iOS with the most current being 10.2.

**Comment by digitaldan** [comment]
Hi @Gibber thanks for the report, we have antoher user with the same issue, I will email him to join this thread so we can git it resolved. Thanks!

**Comment by netzlaff** [comment]
Hello,
I have the same problem. Dan has asked me to report here.
My iOS devices: iPhone 6 and 5S, iPad mini 2 (iOS 10.2 on all devices)
I can only see my iPad under Account / Devices. Broadcast-Notifications are sent to one device only, my iPhone 6.
Thanks for help.

**Comment by digitaldan** [comment]
@Gibber can you email me  the email you used to register so I can look up your account?  Use support@myopnehab.org please.  

@netzlaff it sounds like ios is not registering when connecting, can you confirm here what host you have in the "remote" field on the settings, can you also make sure there are no spaces at the beginning or end of that entry (we might have a bug there).

**Comment by kaikreuzer** [comment]
> Use support@myopnehab.org please.

You will have guessed yourself: It should read support@myopenhab.org :-)

**Comment by netzlaff** [comment]
I've checked all my iDevices, Remote URL is: https://myopenhab.org
I can use my sitemap perfectly, only Notifications and the iOS Registration under my account dosen't work.

**Comment by netzlaff** [comment]
Can i help to solve the problem?

**Comment by tarlen** [comment]
I'm also seeing this issue. iPhone 6S and iPad Air 2, both on iOS 10.2.1, connecting to https://myopenhab.org/.

No items or devices are shown in the myopenhab.org interface, but using the iOS app, I can control my setup remotely.

**Comment by kbsprout** [comment]
Also seeing the issue. iPhone 6S on iOS 10.2. App connects to https://myopenhab.org:8443
My sitemap comes up and I can control devices, but when I log into https://myopenhab.org/devices from a regular browser I see no devices listed. On the App when I try looking at the App's Notifications tab, it is empty and hangs on a swipe-down refresh attempt.

**Comment by kbsprout** [comment]
I don't know if someone just changed something, but my :8443 port stopped working so I tried a few things and removed the port number entirely. Now I can connect from the app to https://myopenhab.org and the Notifications pane is full of listings, and my device shows up on the website, and I even receive actual iOS popup notifications!    This is with both an iPhone6s and an older iPad, both running iOS 10.2.  We'll see if it goes away when I update to 10.2.1

**Comment by tarlen** [comment]
Okay, I believe I've figured out the problem. 

I had the app set with a remote URL of `https://myopenhab.org/`, and when it started up, I was getting a 404 error connecting to `https://myopenhab.org//addAppleRegistration`.

Note the double slash after the domain name?

I changed the remote URL to `https://myopenhab.org` (no trailing slash), and now it's working. My device has appeared in the list, and push notifications are being received.

**Comment by Gibber** [comment]
Yep, that worked for me as well. Thanks!

**Comment by netzlaff** [comment]
Not for me. In my Apps the URL is set to https://myopenhab.org without slash.

**Comment by netzlaff** [comment]
Can anybody help me?
