### ISSUE TITLE
New Logger setup not ideal for docker based installs

### ISSUE THREAD

**Issue by alackmann** [openhab/openhab-cloud#278]
Since PR #224 that improved the logging configurations, as the Express app doesn't log to stdout any longer, logs are not shown via the `docker logs` command for docker based installs of openhab-cloud.

Ideally there would be an additional config option to allow console to still be chosen as a transport. fyi @digitaldan

**Comment by alackmann** [comment]
I have proposed a fix as included it as a part of my PR #276 - as that is required to automate docker builds anyway.

**Comment by marziman** [comment]
Closing this, I am adding auto-build to dockerhub for master and tag latest.

**Comment by marziman** [comment]
Build is now automated and any push to master will trigger a new image creation in dockerhub.

Closing this.
