### ISSUE TITLE
openHAB 3 instances are not recognized

### ISSUE THREAD

**Issue by kaikreuzer** [openhab/openhab-cloud#297]
Just connected my openHAB 3 test instance to myopenHAB and noticed that it is not recognized, since it does not have the openHAB 2 dashboard anymore:

<img width="760" alt="Bildschirmfoto 2020-05-24 um 16 38 58" src="https://user-images.githubusercontent.com/3244965/82756873-18586180-9ddd-11ea-95f3-f8e636b7f9ec.png">

@digitaldan Could you maybe add support for openHAB 3? Would be awesome 😎.

**Comment by digitaldan** [comment]
yep, i noticed that too, i'll take a look today, should be a easy fix.  FYI last time i checked, proxying still worked if you went to home.myopenhab.org or myopenhab.org/rest for example.   I have not tried since we implemented the core oauth layer however.

**Comment by kaikreuzer** [comment]
Great, thanks!
Yes, proxying worked, but interestingly, any POST request to items was answered with a 404. Might be due to the new oauth, but I assume that needs to be handled in the cloud-connector bundle, so I didn't mention it here.

Btw, if you are touching openhab-cloud: Could you maybe also update the copyright footer from 2018 to 2020?

**Comment by digitaldan** [comment]
>Btw, if you are touching openhab-cloud: Could you maybe also update the copyright footer from 2018 to 2020?

Yep, i'll just make that automatic

**Comment by digitaldan** [comment]
See https://github.com/openhab/openhab-cloud/pull/298

This is only a change to the website, so i can deploy without interrupting connections.  I'll take a look at that tonight.  This also is motivating me to get my butt in gear and finish the k8s deployment so this is push button!

**Comment by kaikreuzer** [comment]
@digitaldan Has #298 ever been deployed? I just upgraded my production system to openHAB 3 and now cannot use myopenHAB anymore :-(
It would be awesome if you could do the deployment very soon, thx!

**Comment by digitaldan** [comment]
For some reason this did not deploy correctly, and i had to roll it back (then was distracted and forgot!) .  I am working on cloud stuff this weekend and will see if i  can chase down why this happened.  Hopefully it's something very small.

**Comment by digitaldan** [comment]
I deployed this on Friday, basic poxing works.  What does not work however is using the new authentication in OH3.  I have 2 PR's open to fix this , first is a change to the cloud connector to not try and follow redirects by default, we need 302's to go back to the calling client , see https://github.com/openhab/openhab-addons/pull/8429 .  The second is a change to our cloud code to not use 302's to move a internal request to the right proxy (we will use 307s for that.  See #307.   #307 requires a deploy to our proxy processes , so i will do a slow rolling  deploy for this over the next week after i have finished testing.

**Comment by digitaldan** [comment]
And its just a funny coincidence that the fix is changing the response code to a 307 AND the PR is number #307 :-)

**Comment by digitaldan** [comment]
This has been deployed, please ensure you have the latest nightly of OH 3.0 before testing.
