### ISSUE TITLE
Sign in to openhab ui from openhabcloud not possible (Authorization header clash?)

### ISSUE THREAD

**Issue by TheTrueRandom** [openhab/openhab-cloud#333]
When connecting an openhab 3.0.1 instance to a self hosted or myopenhab.org cloud instance and accessing the openhab dashboard through the 'home.' proxy, it is not possible to sign in as an administrator on the openhab ui. I think this comes from an authorization header clash. When opening the openhab ui locally and signing in, every request contains an authorization header with a bearer token. However when accessing through myopenhab there is already a basic auth header used. So immediately after signing in on the openhab ui accessed through openhabcloud the page is just blank. 

This PR (https://github.com/openhab/openhab-cloud/pull/331) sounds similar but I don't really understand it. Also I tested it and it doesn't fix the issue

**Comment by lsafelix75** [comment]
https://github.com/openhab/openhab-webui/pull/908
This could be another patch that you need.
