### ISSUE TITLE
BUG: INTERNAL SERVER ERROR when pairing alexa skill

### ISSUE THREAD

**Issue by ideaforno10** [openhab/openhab-cloud#337]
News openhab 3 install. Getting an internal server error on myopenhab when trying to enable alexa binding on amazon.com.

**Comment by ideaforno10** [comment]
More reports of this service being down on the discussion board. Please see:

https://community.openhab.org/t/openhab-alexa-skill-internal-server-error/118650

**Comment by digitaldan** [comment]
Thanks

**Comment by digitaldan** [comment]
Fixed, thanks!
