### ISSUE TITLE
Incorrect URL when listening for sitemap events

### ISSUE THREAD

**Issue by tavalin** [openhab/openhab-cloud#34]
I have a switch that is used to hide a sitemap frame.  When clicking it though openhab-cloud it didn't work.
I received the following error message in my web console:

`Firefox can't establish a connection to the server at https://home.openhab.org/rest/sitemaps/events/0982595d-9132-4bb5-800b-bacf5925cf96?sitemap=test&pageid=test.1smarthome.js:1:18688`

h

I assume the address should be `home.myopenhab.org` rather than `home.openhab.org`

**Comment by digitaldan** [comment]
Yes, I see where we missed this.  Thanks for the report.
