### ISSUE TITLE
BasicUI Does not render correctly after S2300.

### ISSUE THREAD

**Issue by morph166955** [openhab/openhab-cloud#344]
When I moved from S2300 to S2304 something broke in respect to the way the cloud connector is pulling the basicui through.  It renders no issues when connecting locally directly to the OH3 server.  I have updated openhab-cloud to the most recent commit and it does not help anything.  To note, it passes through to the openhab app with no issues.  This is only when trying to pull it up through the cloud connector.

EDIT: I tested between S2300 and S2304 and it's broken in S2304.  2301-2303 did not build correctly.  I'm assuming this is related somehow to the OSGi/Karaf updates.

**Comment by digitaldan** [comment]
pretty sure this was fixed in https://github.com/openhab/openhab-addons/pull/10487
