### ISSUE TITLE
Device Name not editable on Website

### ISSUE THREAD

**Issue by hmerk** [openhab/openhab-cloud#35]
I have several devices which broadcast the same hostname over the network and have no possibility to edit the name.
On myopenhab website, it is not possible to register more than one device under a specific name. Trying the "edit" button next to the "delete" button leads to "nothing".

**Comment by digitaldan** [comment]
Yes, looking at the code I see this is not actually implemented, the button looks like a placeholder. Unless I have a volunteer to implement this feature I would advise to remove the button.

**Comment by hmerk** [comment]
Not what I wanted to read :-(

**Comment by FlorianSW** [comment]
What do you want to edit if you click on the edit button? Isn't the registration ID the unique identifier for the device, so why can't you add two devices out of the same network? :)

**Comment by hmerk** [comment]
I have three devices of the same type, where I cannot edit their names.
This lead to the issue, only seeing the last registered one in myopenhab.

**Comment by FlorianSW** [comment]
Hmm, even if I think it should be possible to have a custom name for a device (it shouldn't be customizable to edit the device model, of course, so it would be another field), it should already be possible to register several devices of the same type:
![image](https://cloud.githubusercontent.com/assets/4892966/25594623/a80f9174-2ec1-11e7-91b3-bb75b4ed45b7.png)

Do you get an error message or do you simply see only one device? Is it an apple or android device (I tested it with android)?

**Comment by hmerk** [comment]
Those are Android devices and I just don't see two of them.

**Comment by marziman** [comment]
Will look into this soon @hmerk and @FlorianSW and if missing trying to implement it.
Just have some other PRs in the first line before.

**Comment by gonzaechev** [comment]
> Hmm, even if I think it should be possible to have a custom name for a device (it shouldn't be customizable to edit the device model, of course, so it would be another field), it should already be possible to register several devices of the same type:
> ![image](https://cloud.githubusercontent.com/assets/4892966/25594623/a80f9174-2ec1-11e7-91b3-bb75b4ed45b7.png)
> 
> Do you get an error message or do you simply see only one device? Is it an apple or android device (I tested it with android)?

Hi, change device name in MongoDb (devices collection)
I tried this and works
