### ISSUE TITLE
Change link to privacy policy

### ISSUE THREAD

**Issue by MHerbst** [openhab/openhab-cloud#37]
The login page https://myopenhab.org/ contains a link to the privacy policy on www.openhabfoundation.org:
![image](https://cloud.githubusercontent.com/assets/616792/22606767/5f9e6de4-ea55-11e6-9ab5-284e558156b1.png)

Now www.myopenhab.org has its own privacy policy page and therefore it would be much better to use this page: http://www.myopenhab.org/privacy.

**Comment by marziman** [comment]
Hi @MHerbst,

thanks but this is not a oh cloud issue, since this can be set in the config properties field under legal. Since myoh is a adjusted version of oh cloud, this should not be adressed here.

**Comment by MHerbst** [comment]
Hi @marziman ,
Thank you for the information. That's the reason why I could not find the link text here.
