### ISSUE TITLE
issue on windows

### ISSUE THREAD

**Issue by ppyoosuf** [openhab/openhab-cloud#38]
i have configured every required application.but server not running

**Comment by marziman** [comment]
Hello ppyoosuf,
if you have an issue please add some log and describe your problem more precise. Otherwise we cant really help.
If it is not an issue, more sth. like a setup problem etc. it is better to make a forum post. You will get help there: https://community.openhab.org
If you find issues or bugs or enhancements, feel free to add them here.
Thanks a lot!
BR Mehmet

**Comment by ppyoosuf** [comment]
**this is my error 



E:\yoosuf\Open HAB Sorces\openhab-cloud-master\openhab-cloud-master>node app.js
2017-02-04T14:40:01.543Z - info: openHAB-cloud: Backend service is starting up...
2017-02-04T14:40:01.562Z - info: openHAB-cloud: Backend logging initialized...
2017-02-04T14:40:01.979Z - error: uncaughtException: Cannot find module 'node-xmpp' date=Sat Feb 04 2017 20:10:01 GMT+0530 (India Standard Time), pid=7140, uid=null, gid=nul
l, cwd=E:\yoosuf\Open HAB Sorces\openhab-cloud-master\openhab-cloud-master, execPath=C:\Program Files\nodejs\node.exe, version=v5.10.1, argv=[C:\Program Files\nodejs\node.ex
e, E:\yoosuf\Open HAB Sorces\openhab-cloud-master\openhab-cloud-master\app.js], rss=30810112, heapTotal=18141616, heapUsed=11575256, loadavg=[0, 0, 0], uptime=379554.4821285
, trace=[column=15, file=module.js, function=Function.Module._resolveFilename, line=339, method=Module._resolveFilename, native=false, column=25, file=module.js, function=Fu
nction.Module._load, line=290, method=Module._load, native=false, column=17, file=module.js, function=Module.require, line=367, method=require, native=false, column=19, file
=internal/module.js, function=require, line=16, method=null, native=false, column=12, file=Sorces\openhab-cloud-master\openhab-cloud-master\gcm-xmpp.js, function=Object.<ano
nymous> (E:\yoosuf\Open HAB, line=11, method=<anonymous> (E:\yoosuf\Open HAB, native=false, column=34, file=module.js, function=Module._compile, line=413, method=_compile, n
ative=false, column=10, file=module.js, function=Object.Module._extensions..js, line=422, method=Module._extensions..js, native=false, column=32, file=module.js, function=Mo
dule.load, line=357, method=load, native=false, column=12, file=module.js, function=Function.Module._load, line=314, method=Module._load, native=false, column=17, file=modul
e.js, function=Module.require, line=367, method=require, native=false, column=19, file=internal/module.js, function=require, line=16, method=null, native=false, column=17, f
ile=Sorces\openhab-cloud-master\openhab-cloud-master\app.js, function=Object.<anonymous> (E:\yoosuf\Open HAB, line=39, method=<anonymous> (E:\yoosuf\Open HAB, native=false,
column=34, file=module.js, function=Module._compile, line=413, method=_compile, native=false, column=10, file=module.js, function=Object.Module._extensions..js, line=422, me
thod=Module._extensions..js, native=false, column=32, file=module.js, function=Module.load, line=357, method=load, native=false, column=12, file=module.js, function=Function
.Module._load, line=314, method=Module._load, native=false], stack=[Error: Cannot find module 'node-xmpp',     at Function.Module._resolveFilename (module.js:339:15),     at
 Function.Module._load (module.js:290:25),     at Module.require (module.js:367:17),     at require (internal/module.js:16:19),     at Object.<anonymous> (E:\yoosuf\Open HAB
 Sorces\openhab-cloud-master\openhab-cloud-master\gcm-xmpp.js:11:12),     at Module._compile (module.js:413:34),     at Object.Module._extensions..js (module.js:422:10),
 at Module.load (module.js:357:32),     at Function.Module._load (module.js:314:12),     at Module.require (module.js:367:17),     at require (internal/module.js:16:19),
 at Object.<anonymous> (E:\yoosuf\Open HAB Sorces\openhab-cloud-master\openhab-cloud-master\app.js:39:17),     at Module._compile (module.js:413:34),     at Object.Module._e
xtensions..js (module.js:422:10),     at Module.load (module.js:357:32),     at Function.Module._load (module.js:314:12)]
2017-02-04T14:40:01.981Z - error:  code=MODULE_NOT_FOUND

when i tried to install node-xmpp but it not generating any folder inside of the node_modules**

E:\yoosuf\Open HAB Sorces\openhab-cloud-master\openhab-cloud-master\node_modules\node-expat\build\deps\libexpat\expat.vcxproj(19,3): error MSB4019: The imported project "E:
\Microsoft.Cpp.Default.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
