### ISSUE TITLE
Firebase API is deprecated and will be removed at June 20, 2024

### ISSUE THREAD

**Issue by Pizzaschachtel** [openhab/openhab-cloud#446]
Hi,

I got a notification from firebase, that the Cloud Messaging API will be removed at June 20, 2024. If I see this correctly, than openhab-cloud uses the legacy API to send push notifications to android devices. At June 20, 2024 no messages will be delivered anymore.

So are there any plans to migrate to the new V1-API? I already asked that in the community, but I didn't get a lot of response, maybe because I wrote it in an already existing topic with "Tutorial" in the title  https://community.openhab.org/t/tutorial-own-openhab-cloud-and-gcm-notifications-firebase/38287/17?u=marcusspors 

Best regards

**Comment by digitaldan** [comment]
Hi thanks for the heads up, yes i plan on migrating us before this gets shut off.

**Comment by Pizzaschachtel** [comment]
Hi dan, that sounds good. Can I help you? I'm a android/ios/backend developer and I'm familar with nodeJS. 
If I see it correct, we have to make changes in the following files:
* notificationsender/firebase.js
* fcm-xmpp.js (depreacted?)
-> and we have to use a newer framework for firebase https://www.npmjs.com/package/@firebase/messaging instead of firebase-messaging
What also come in my mind is, that we have to change/adopt the configuration file, so that it is possible to put path to key files for firebase in it.

But I don't know how to start, because this would be my first pull request on open source projects. I appreciate any advice

**Comment by mueller-ma** [comment]
Any update on this? It's only one month left until the shutdown of the legacy API.

**Comment by digitaldan** [comment]
Hey @mueller-ma , let me email you, we have an issue still will our firebase id's, will need to come up with a solution before we can move API's i think.

**Comment by mueller-ma** [comment]
This issue can be closed now as FCM has been migrated.
