### ISSUE TITLE
absolute url in openhab-cloud/views/index.ejs

### ISSUE THREAD

**Issue by github-luckow-org** [openhab/openhab-cloud#45]
Hi, 

it's not the best idea to have an absolute url in

 /$DIR/openhab-cloud/views/index.ejs

> case 'online':
>                             if (openhabMajorVersion == '2') {
>                 %>
>                                 You are using openHAB 2.x. <a href="https://home.myopenhab.org/start/index">Click here to access your openHAB's dashboard</a>

Please change it to a relative url or use the base-url from config.json. Same for openHAB 1.x link.

**Comment by marziman** [comment]
@github-luckow-org ,

thanks. There will be a config property for this the next days.
BR Mehmet
