### ISSUE TITLE
Reconnecting to cloud

### ISSUE THREAD

**Issue by iPavel89-work** [openhab/openhab-cloud#465]
Hello. I updated openhabcloud server and now if I restart cloud service sometimes i have error
Error connecting to the openHAB Cloud instance: already connected

and i can solve problem only if restart openhab service in client. How can I solve problem? Also sometimes if I have same problem when openhab client lost internet connection

**Comment by digitaldan** [comment]
This is an issue with the cloud server code https://github.com/openhab/openhab-cloud, not the binding.  When the server shuts down it does not gracefully disconnect sessions, we keep a 2 min keep alive lock, if we don't get a heart beat from the client in 2 mins, then redis releases the lock.  So the client should connect after 2 mins.    Its something i have been thinking about trying to fix as its a minor inconvenience when we deploy new versions of the code and have to restart.

**Comment by iPavel89-work** [comment]
I made script. Script send request to cloud. if response  is "Openhab offline"  script restart openhabcloud connector
