### ISSUE TITLE
Integrate Documentation in openhab-docs

### ISSUE THREAD

**Issue by cniweb** [openhab/openhab-cloud#5]
Integrate Documentation about installation and configuration in https://github.com/openhab/openhab-docs

**Comment by cniweb** [comment]
@marziman is the openHAB1 configuration the same as in my.openhab.org?
Must we integrate the old openHAB1 documentation:
https://my.openhab.org/docs
to the new?
here:
https://github.com/openhab/openhab-docs/tree/gh-pages/addons/io/openhabcloud
I can do it!

**Comment by marziman** [comment]
@cniweb:
my.openhab.org/docs is deprecated. For OH1 there is this version:
OH1:
https://github.com/openhab/openhab/wiki/openHAB-Cloud-Connector

**Comment by cniweb** [comment]
OK, but I think, we must add a little documentation page with link to OH1 and OH2 documentation!

**Comment by kaikreuzer** [comment]
Guys, I think this issue is about the documentation of "setting up an openHAB Cloud instance" - I think the readme on this repo is just fine for that, I am not sure that it should be added to docs.openhab.org at all as it is something very specific.

Don't mix the documentation up with the cloud connector bundle, which is already in place (and will be used by 99% of the users for myopenHAB) and I do not see a need to change anything there.

**Comment by kaikreuzer** [comment]
>https://my.openhab.org/docs

This has actually been moved to http://www.myopenhab.org - but you can feel free to add parts from that to the README.md in this repo as well.

**Comment by marziman** [comment]
@kaikreuzer ,
I may add some more infos about the whole E2E chain, after setup of an instance. Cause than you want to connect your device usually.
For the connector, I think the users will have difficulties with to places of docu for OH1 and OH2 cloud connector.

**Comment by kaikreuzer** [comment]
> For the connector, I think the users will have difficulties with to places of docu for OH1 and OH2 cloud connector.

What do you mean exactly? Finding the connector docs?

**Comment by marziman** [comment]
@cniweb @kaikreuzer,
I will close this Issue and open a new one (for the extension of this docu with more infos about the connector), since we re not going to add this to docs.openhab.org? Do you agree?

**Comment by marziman** [comment]
@kaikreuzer yes, but I recognized they are at the addons docu for both, the place to be.

**Comment by marziman** [comment]
Closing this issue, since there is a new one for the extension regarding connector.
