### ISSUE TITLE
In devices page, point user towards how to register a device

### ISSUE THREAD

**Issue by ShaunCurrier** [openhab/openhab-cloud#51]
Using a myopenhab.org URL as an example... https://myopenhab.org/devices

If you have no registered devices, the page only says,
"You currently have no devices registered with openHAB Cloud."
It is not clear how a device becomes registered.  I believe some users (me included) would expect registration to be done the system that is taking the registration, the cloud instance web site in this case.  But counter-intuitively, registration instead is done from the device.  So it would help to nudge the user in the right direction for how to resolve the "no devices registered" problem that we know they are encountering when they see that message.

It would be better if it said something like,
"You currently have no devices registered with openHAB Cloud.  To register a device, set the remote URL, myopenhab.org username, and myopenhab.org password in the device's app.  The remote URL should be set to https://myopenhab.org."
...replacing the URL reference with whatever the proper base URL is for the particular cloud instance.

**Comment by marziman** [comment]
@ShaunCurrier 
we have a PR for this in the making. Should be extended soon. Thanks for your help!
BR Mehmet
