### ISSUE TITLE
Can't access paperui

### ISSUE THREAD

**Issue by ryanrdetzel** [openhab/openhab-cloud#58]
Get an error

Cannot GET /paperui/index.html

**Comment by kaikreuzer** [comment]
This definitely works. Try to ask for support at https://community.openhab.org/.

**Comment by digitaldan** [comment]
Hi, try using https://home.myopenhab.org/paperui/index.html

**Comment by ryanrdetzel** [comment]
Maybe I should have stated, "when you run your own instance it does not work"
