### ISSUE TITLE
Notifications on Habdroid not working

### ISSUE THREAD

**Issue by kobelka** [openhab/openhab-cloud#67]
With the openhab-cloud installed on my own server I get no notifications on the habdroid app anymore.
Regards 
Kobelka

**Comment by jblancoperez** [comment]
I have installed a new instance . I created a new firebase application. Changed the gcm id and secret in the server .

Compiled a new habdroid version with this new gcm id, but cannot make it work.

Server registers into gcm but no app appears I. The devices page.

I am missing something?

**Comment by ranger36** [comment]
Hi,

Been struggling with this myself. Everything running fine on own cloud server except from the google and ifttt notifications. Can anyone shed some light as to how to set this up?

thanks

**Comment by digitaldan** [comment]
For IFTTT you will need to register with IFTTT as a service provider, I don't know if they do this for individuals, typically this is only for actual cloud providers (Smartthings, Amazon, openHAB Foundation, etc...).  If they do accept you into their program you will need to setup the oauth keys so your user(s) can link accounts.

Android notifications will require you to register a GCM key on your google dev account, add that to your cloud config and then also add that to your android build which you will need to distribute yourself. 

Note that these restrictions our not own making but just the realities of working with third party providers.

**Comment by digitaldan** [comment]
>Compiled a new habdroid version with this new gcm id, but cannot make it work.

You will also need to change the code to detect your cloud URL otherwise it will not register, right now we are looking for myopenhab (or openhab.org, can't remember) in the remote URL.

**Comment by hakan42** [comment]
@ranger36 , maybe you could integrate with the Maker channel of IFFT?v

https://ifttt.com/blog/2015/06/introducing-the-maker-channel

**Comment by ranger36** [comment]
Fantastic Dan. Got the gcm working now by changing openhabmainactivity.java line 1201 to my own domain. Many thanks

**Comment by ranger36** [comment]
@hakan42. Thanks for that. will have a look at it

**Comment by Frodo69** [comment]
So for those looking to set up OpenHAB-Cloud notifications, here is a quick summary of what needs to be done.

Jid = Your_Sender_Key@googleapis.com
Password = server key
I don't know if the legacy server key will work, I used the server key from Firebase console, also make sure you use the keys on the "Cloud Messaging" tab!

Before compiling habdroid"
Change OpenHABMainActivity.java line 145 and 1201 to match your system.

**Comment by jblancoperez** [comment]
Working as expected after applying @Frodo69  procedure.
