### ISSUE TITLE
Installing Problem on Ubuntu 14.04

### ISSUE THREAD

**Issue by badplay** [openhab/openhab-cloud#69]
Hi

i am stack at : Now you need install git and clone the openHAB Cloud repository to your preferred directory (here: ubuntu) with the following commands:

apt-get install git
cd /home/YOUR-DIR/
git clone https://github.com/openhab/openhab-cloud.git

with terminal i made mkdir /home/ubuntu
then i go to cd /home/ubuntu/

then i use the git clone with root rights

this works but the next in the installation tut isnt working 

`admin@ubuntu-hd:~$ sudu su
bash: sudu: command not found
admin@ubuntu-hd:~$ sudo su
[sudo] password for admin: 
root@ubuntu-hd:/home/admin# cd openhabcloud
bash: cd: openhabcloud: No such file or directory
root@ubuntu-hd:/home/admin# cd /home/ubuntu/
root@ubuntu-hd:/home/ubuntu# cd openhabcloud
bash: cd: openhabcloud: No such file or directory
root@ubuntu-hd:/home/ubuntu# cd /openhabcloud
bash: cd: /openhabcloud: No such file or directory
root@ubuntu-hd:/home/ubuntu# git clone https://github.com/openhab/openhab-cloud.git
fatal: destination path 'openhab-cloud' already exists and is not an empty directory.
root@ubuntu-hd:/home/ubuntu# cd openhabcloud
bash: cd: openhabcloud: No such file or directory
root@ubuntu-hd:/home/ubuntu# ls -d */
openhab-cloud/
root@ubuntu-hd:/home/ubuntu# cd openhab-cloud
root@ubuntu-hd:/home/ubuntu/openhab-cloud# node -v
bash: node: command not found
root@ubuntu-hd:/home/ubuntu/openhab-cloud# node --version
bash: node: command not found
root@ubuntu-hd:/home/ubuntu/openhab-cloud# npm install
bash: npm: command not found

`

**Comment by digitaldan** [comment]
Hi, as mentioned in another issue, this project is geared towards developers and advanced users, my guess is you want to use the hosted version at https://myopenhab.org which has IFTTT and Alexa integration (ifttt would not be easily possible on a self hosted version).
