### ISSUE TITLE
Installing OpenHAB CLoud on Qnap Nas with Ubuntu Linux Station

### ISSUE THREAD

**Issue by badplay** [openhab/openhab-cloud#70]
I try to install and use your installation tut. but i get so many errors i cant set up so many things dont know how i can do it :( i am a noob at ubuntu

but i need open hub cloud for ifttt and amazon alexa

**Comment by digitaldan** [comment]
Please use the hosted version at https://myopenhab.org , this is the source code for our service, but is only intended to be run by developers or advanced users that can setup their own cloud environment.
