### ISSUE TITLE
Old password not required on password change

### ISSUE THREAD

**Issue by koenbuyens** [openhab/openhab-cloud#74]
Description:
 Password change should require the old password. Without the old password, an attacker who is able to execute an XSS attack (or with physical access to the computer) may be able to impersonate the user.

Steps to reproduce:
1. Authenticate.
2.  Go to <baseurl>/account
3. Enter the new password twice. Click on 'Change'. 
4. Observe that the password has been successfully changed.

Mitigation:
Asks users for their old password and verify it before changing the password.

More info: https://www.owasp.org/index.php/Authentication_Cheat_Sheet#Require_Re-authentication_for_Sensitive_Features

**Note**:  It would be nice if there is a way to send security issues to openhab via an alternate communication channel (e.g. security@openhab.org). This avoids that attackers are able to get knowledge of more serious security issues before they are fixed.

**Comment by digitaldan** [comment]
Hi @koenbuyens thanks, you are correct the app should require the old password on change

**Comment by FlorianSW** [comment]
I'll take this one :)
