### ISSUE TITLE
Improper password strength controls

### ISSUE THREAD

**Issue by koenbuyens** [openhab/openhab-cloud#75]
Description:
A strong password is a key requirement to protect against password guessing attacks. The application does not implement a strong password policy, as users can create an account with a password of one character.

Steps to reproduce (A):
1. Authenticate
2. Go to <baseurl>/account
3. Enter a new password of one character, e.g. 'a'.
4. Save
5. Logout
6. Authenticate with the same user and the new password. Observe that this worked.

More information: https://www.owasp.org/index.php/Authentication_Cheat_Sheet#Implement_Proper_Password_Strength_Controls

**Comment by digitaldan** [comment]
Yes, that is troublesome, thanks for reporting.
