### ISSUE TITLE
User enumeration

### ISSUE THREAD

**Issue by koenbuyens** [openhab/openhab-cloud#76]
An attacker is able to enumerate usernames. This is one of the two pieces of information required to authenticate.

Steps to reproduce:
1. Go to <baseurl>/lostpassword
2. Enter an email address that does not exist.  Observe the error message.
![image](https://cloud.githubusercontent.com/assets/17049884/24833121/942c1506-1c8d-11e7-9414-c0aa71971c19.png)
3. Enter an email address that exists. Observe the message.
![image](https://cloud.githubusercontent.com/assets/17049884/24833129/c327e754-1c8d-11e7-90ad-3cbc0f49075a.png)
4. As both messages are different, an attacker is able to obtain a list of usernames.

Mitigation:
Change the message to something like 'We sent a password reset link to your email address if it exists'. Redirect to the same URI when finished.

More info: https://www.owasp.org/index.php/Authentication_Cheat_Sheet#Authentication_and_Error_Messages

**Comment by digitaldan** [comment]
Yep, we should not be displaying separate messages.
